--A_NEW_DB_FORMING 

CREATE DATABASE FIRST_PROJECT;

--FORMING_NEW_TABLE_INTO_DB

CREATE TABLE FIRST_PROJECT.TABLE_01
(EMPLOYEE_ID SERIAL PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(100) NOT NULL,
AGE INT,
DEPARTMENT VARCHAR(100) NOT NULL,
EXPERIENCE INT,
SALARY DECIMAL);

--INSERTING_DATA_INTO_DB

INSERT INTO FIRST_PROJECT.TABLE_01
(EMPLOYEE_NAME,AGE,DEPARTMENT,EXPERIENCE,SALARY) 
VALUES
('A KR',30,'BANKING',3,15000),
('B KR',32,'SALES',4,17800),
('C KR',35,'FINANCE',6,13910),
('D KR',33,'MARKERING',6,19879),
('E KR',36,'LOAN',3,10950),
('F KR',37,'MARKETING',4,19890),
 ('G KR',32,'BANKING',2,15610),
('H KR',31,'BANKING',3,19878),
 ('I KR',30,'LOANS',3,19890),
 ('J KR',38,'SALES',5,18757);
 
 SELECT * FROM FIRST_PROJECT.TABLE_01

--RETRIEVE_SHOW_ALL_EMPLOYEE_NAME_AND_THEIR_DEPARTMENT

SELECT EMPLOYEE_NAME,DEPARTMENT FROM FIRST_PROJECT.TABLE_01;

--DELETE_ALL_EMPLOYEE_WHO_ARE_OLDER_THAN_34

 DELETE FROM FIRST_PROJECT.TABLE_01
 WHERE AGE>34;
 
 --DELETING_TABLE_THAT_EXIST
 
 DROP TABLE IF EXISTS FIRST_PROJECT.TABLE_01
 
 --UPDATE_THE_SALARY_OF_ALL_THE_BANKING_EMPLOYEE_BY_10%
 
UPDATE FIRST_PROJECT.TABLE_01
SET SALARY=SALARY+(SALARY*0.2)
WHERE DEPARTMENT= 'BANKING';

--ADD_A_NEW_COLUMN_EMAIL_TO_TABLE_01

ALTER TABLE FIRST_PROJECT.TABLE_01
ADD COLUMN EMAIL VARCHAR(100);

--RENAME_COLUMN_DEPARTMENT_TO_DEPT_NAME

ALTER TABLE FIRST_PROJECT.TABLE_01
RENAME COLUMN DEPARTMENT TO DEPT_NAME;

--RETRIVE_THE_NAME_OF_EMPLOYEES_WHOS_SALARY_IS_MORE_THAN_18000

SELECT SALARY FROM FIRST_PROJECT.TABLE_01
WHERE SALARY>18000;

--CHANGE_THE_DATA_TYPE_OF_SALARY_COLUMN_TO_INTEGER

ALTER TABLE FIRST_PROJECT.TABLE_01
MODIFY COLUMN SALARY INTEGER;

--LIST_ALL_EMPLOYEE_WITH_THEIR_AGE_AND_SALARY_IN_DECENDING_ORDER_OF_SALARY

SELECT EMPLOYEE_NAME,AGE,SALARY FROM FIRST_PROJECT.TABLE_01
ORDER BY SALARY DESC;

--INSERTING_A_NEW_EMPLOYEE_WITH_FOLLOWING_DETAILS_Z KR_30_BANKING_3_50000

INSERT INTO FIRST_PROJECT.TABLE_01(EMPLOYEE_ID,EMPLOYEE_NAME,AGE,DEPT_NAME,EXPERIENCE,SALARY)
VALUE('Z KR',38,'SALES',9,58757);

--UPDATE_AGE_OF_EMPLOYEE_1_TO_EVERY_EMPLOYEE

UPDATE FIRST_PROJECT.TABLE_01
SET AGE=AGE+1;



